source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'NAExpandableTableController_Example' do
  pod 'NAExpandableTableController', :path => '../'
end

target 'NAExpandableTableController_Tests' do
  pod 'NAExpandableTableController', :path => '../'

end
