source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'NAExpandableTableController_Example', :exclusive => true do
  pod 'NAExpandableTableController', :path => '../'
end

target 'NAExpandableTableController_Tests', :exclusive => true do
  pod 'NAExpandableTableController', :path => '../'

  
end
